board/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

board/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts' 

urlpatterns = [

    # Read
    path('', views.index, name='index'), 
    path('<int:id>/', views.detail, name='detail'),

    # Create
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # Delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # Update
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
    

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    #post에서 urls로 보낸다
]

posts/urls.py
from django.urls import path
from . import views # . 으로 적은 이유는 내가 위치하고 있는 곳에서 가져오기 위해

app_name = 'posts' # 장고 내부에서 정해 놓은 것이며, 각각의 핼동을 지정해줄수 있다?

urlpatterns = [
    
    # Read
    path('', views.index, name='index'), #여떤 데이터를 넣어도 posts의 데이터를 가져온다.
    path('<int:id>/', views.detail, name='detail'),

    # Create
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # Delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # Update
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),

]

board/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

posts/models.py
from django.db import models

# Create your models here.

class post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

board/posts/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.

def index(request):
        posts = Post.objects.all()

        context = {
                'posts': posts,

        }
        return render(request, 'index.html', context)

def detail(request, id):
        post = Post.objects.get(id=id)

        context = {
                'post': post,

        }

        return render(request, 'detail.html', context)

def new(request):
        return render(request, 'new.html')

def create(request):
        title = request.POST.get('title')
        content = request.POST.get('content')

        post = Post(title=title, content=content)
        post.save()

        return redirect('posts:detail', id=post.id)

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()

    return redirect('posts:index')


def edit(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post,
    }
    
    return render(request, 'edit.html', context)


def update(request, id):
    # new data
    title = request.POST.get('title')
    content = request.POST.get('content')

    # old data
    post = Post.objects.get(id=id)
    post.title = title
    post.content = content
    post.save()

    return redirect('posts:detail', id=post.id)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.

def index(request):
        posts = Post.object.all()

        context = {
                'posts': posts,

        }


        return render(request, 'index.html', context)

def detail(request, id):
        post = Post.objects.get(id-id)

        context = {
                'post': post,

        }

        return render(request, 'index.html', context)

def new(request):
        return render(request, 'new.html')

def create(request):
        title = request.POST.get('title')
        content = request.POST.get('content')

        # post = Post()
        # post.title = title
        # post.content = content
        # post.save()
        # 아래랑 같은 코드
        post = Post(title=title, content=content)
        post.save()

        return redirect('posts:detail', id=post.id)

def delete(request, id):
        post = Post.objects.get(id=id)
        post.delete

        return redirect('posts:index')

def editre(request, id):
        post = Post.objects.get(id=id)

        context = {
                'post':post,
        }
        return render(request,'edit.html', context) 

def update(request, id):
        title = request.POST.get('title')
        content = request.POST.get('content')

        post = Post.objects.get(id=id)
        post.tilte = title
        post.content = content
        post.save()

        return redirect('post:detail', id=post.id)

board/posts/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="coard-header">
        {{post.title}}

    </div>
    <div class="coard-body">
        {{post.content}}

    </div>
    <div class="coard-footer">
        <p>{{post.created_at}}</p>
        <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-danger">delete</a>
        <a href="{% url 'posts:edit' id=post.id %}" class="btn btn-warning" >edit</a>

    </div>

</div>


{% endblock %}

board/posts/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>제목</th>
                <th>상세보기</th>

            </tr>
        </thead>
        
        <tbody>
            {% for post in posts %}
                <tr>
                    <td>{{post.title}}</td>
                    <td> <a href="{% url 'posts:detail' id=post.id %}">detail</a></td> 
                </tr>

            {% endfor %}

        </tbody>

    </table>

{% endblock %}

board/posts/templates/new.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="form-control" id="title" name="title">
    </div>

    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
      <textarea class="form-control" id="content" cols="30" rows="10" name="content"></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

board/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'posts:index' %}">home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'posts:new' %}">create</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
          </div>
        </div>
      </nav>

      <div class="container">
        {% block content %}
        {% endblock %}
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="card">
        <div class="coard-header">
            {{post.title}}

        </div>
        <div class="coard-body">
            {{post.content}}

        </div>
        <div class="coard-footer">
            <p>{{post.created_at}}</p>
            <a href="{% url 'posts:delete' id=post.id %}" class="btn btn-danger">delete</a>
            <a href="{% url ;posts:edit' id=post.id %}" class="btn btn-warning" >edit</a>

        </div>

    </div>


{% endblock %}

posts/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'post:update' id=post.id %}" method="POST">
    {% csrf_token %}
    <!-- 안전하게 데이터를 저장하기 위해 csrf라는 인증 도장을 찍는다. -->
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="form-control" id="title" name="title" value="{{post.title}}">
    </div>
    
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea class="form-control" name="content" id="content" cols="30" rows="10">{{post.content}}</textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

(% endblock %)

posts/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>제목</th>
                <th>상세보기</th>

            </tr>
        </thead>
        
        <tbody>
            {% for post in posts %}
                <tr>
                    <td>{{post.title}}</td>
                    <td> <a href="{% url 'posts:detail' id=post.id %}">detail</a></td> 
                    <!-- 상세보기 링크 -->
                </tr>

            {% endfor %}

        </tbody>

    </table>

{% endblock %}

posts/templates/new.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'post:create' %}" method="POST">
    {% csrf_token %}
    <!-- 안전하게 데이터를 저장하기 위해 csrf라는 인증 도장을 찍는다. -->
    <div class="mb-3">
      <label for="title" class="form-label">제목</label>
      <input type="text" class="form-control" id="title" name="title">
    </div>
    
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea class="form-control" name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

(% endblock %)

templates/basd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <!-- <a class="navbar-brand" href="/posts/">home</a> -->
          <a class="navbar-brand" href="{% url 'posts:index' %}">home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'posts:new' %}">create</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
          </div>
        </div>
      </nav>

      <div class="container">
        {% block content %}
        {% endblock %}
      </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block content %}

    {{post.title}}
    {{post.content}}
    {{post.created_at}}

{% endblock %}